### PR TITLE
Add Arabic Translation

### PR DESCRIPTION
**Pull request by Alotaibi1217**
Added Arabic translation to the country names list

### CODE REVIEW

**Comment by GeorgeHop** [comment]
Hi! Thanks I will merge it soon.

**Comment by GeorgeHop** [comment]
Checkout please this PR: https://github.com/GeorgeHop/react-native-country-codes-picker/pull/28

**Comment by Alotaibi1217** [comment]
Our formal Arabic language is the same for all Arabic-speaking countries,
so adding only AR translation will do the job

**Comment by GeorgeHop** [comment]
Okay but key AR already used by Argentina so probably we should add some custom key.

**Comment by GeorgeHop** [comment]
Probably it requires some RTL stuff?

**Pull request merged**
