### PR TITLE
Ar

### PR DESCRIPTION
**Pull request by oi19**

### CODE REVIEW

**Comment by GeorgeHop** [comment]
Thank you for your PR? May you provide please anu description?

**Review by yousifalraheem — APPROVED** [review]

**Comment by yousifalraheem** [comment]
This PR adds support for Arabic language, can we get this merged? I really need this 🙏🏻

**Comment by GeorgeHop** [comment]
I will try to merge and publish it today. Little bit confusing why this PR with one new lang includes so many changes.

**Comment by oi19** [comment]
sure , which commit ?

**Pull request merged**
